default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metatags_api_development
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

test:
  <<: *default
  database: metatags_api_test
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

production:
  <<: *default
  database: metatags_api_production
  username: metatags_api
  password: <%= ENV['METATAGS_API_DATABASE_PASSWORD'] %>
