default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metaatags_api_development
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

test:
  <<: *default
  database: metaatags_api_test
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: metaatags_api_production
